name: QAAutomationLabs.com Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress Cloud Tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving Cypress Cloud hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 2 copies of the current job in parallel
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: QAAutomationLabs.com Tests
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          group: 'QAAutomationLabs'
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the GitHub token lets this action correctly
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}